name: Generate Index Page

on:
  push:
    branches: [ main ]
    paths: '**.html'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Index
        run: |
          echo '<!DOCTYPE html>' > index.html
          echo '<html lang="en">' >> index.html
          echo '<head>' >> index.html
          echo '<meta charset="UTF-8">' >> index.html
          echo '<title>Tools</title>' >> index.html
          echo '<link rel="stylesheet" href="styles.css">' >> index.html
          echo '</head>' >> index.html
          echo '<body>' >> index.html
          echo '<h1>Tools</h1>' >> index.html
          echo '<ul>' >> index.html
          for file in $(find . -name "*.html" ! -name "index.html"); do
            name=$(basename "$file" .html)
            echo "<li><a href=\"${file:2}\">$name</a></li>" >> index.html
          done
          echo '</ul>' >> index.html
          echo '</body>' >> index.html
          echo '</html>' >> index.html
      
      - name: Commit and Push
        run: |
          git config --global user.name 'bort actions'
          git config --global user.email 'nwbort@github.com'
          git add index.html
          git commit -m "Update index.html" || exit 0
          git push